[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A tool for installing and managing Kubernetes clusters."
homepage = "https://github.com/InQuicker/kaws"
keywords = ["kubernetes", "coreos", "aws", "terraform", "infrastructure"]
license = "MIT"
name = "kaws"
readme = "README.md"
repository = "https://github.com/InQuicker/kaws"
version = "0.1.0"

[dependencies]
ansi_term = "0.7.2"
clap = "2.1.2"
env_logger = "0.3.2"
log = "0.3.5"
rusoto = "0.12.1"
