[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Create and manage Kubernetes clusters on AWS using Terraform."
homepage = "https://github.com/InQuicker/kaws"
keywords = ["kubernetes", "coreos", "aws", "terraform", "infrastructure"]
license = "MIT"
name = "kaws"
readme = "README.md"
repository = "https://github.com/InQuicker/kaws"
version = "0.6.2"

[dependencies]
ansi_term = "0.9.0"
clap = "2.20.1"
env_logger = "0.4.0"
hyper = "0.10.4"
log = "0.3.6"
rustc-serialize = "0.3.22"
serde = "0.9.6"
serde_derive = "0.9.6"
serde_json = "0.9.5"
tempdir = "0.3.5"

[dependencies.rusoto]
features = ["kms"]
version = "0.23.0"
