#cloud-config

---
coreos:
  etcd2:
    name: ${name}
    initial_cluster: etcd_01=http://10.0.1.4:2380,etcd_02=http://10.0.1.5:2380,etcd_03=http://10.0.1.6:2380
    initial_cluster_state: ${initial_cluster_state}
    initial_advertise_peer_urls: http://$private_ipv4:2380
    listen_peer_urls: http://$private_ipv4:2380
    listen_client_urls: http://$private_ipv4:2379,http://127.0.0.1:2379
    advertise_client_urls: http://$private_ipv4:2379
    data_dir: /var/lib/etcd2/data
  fleet:
    etcd_servers: http://127.0.0.1:2379
    metadata: etcd=quorum,kubernetes=none
    public_ip: $private_ipv4
  units:
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 10-wait-ebs.conf
          content: |
            [Unit]
            Requires=var-lib-etcd2.mount
            After=var-lib-etcd2.mount
    - name: fleet.service
      command: start
    - name: format-etcd-ebs.service
      command: start
      content: |
        [Unit]
        Description=Formats EBS volume for etcd data
        Requires=dev-xvdf.device
        After=dev-xvdf.device
        ConditionPathExists=!/dev/disk/by-label/ETCD
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/wipefs /dev/xvdf
        ExecStart=/usr/sbin/mkfs.ext4 -L ETCD /dev/xvdf
    - name: var-lib-etcd2.mount
      command: start
      content: |
        [Unit]
        Description=Mount EBS volume to /var/lib/etcd2
        Requires=format-etcd-ebs.service
        After=format-etcd-ebs.service
        [Mount]
        What=/dev/xvdf
        Where=/var/lib/etcd2
        Type=ext4
    - name: create-etcd2-data-dir.service
      command: start
      content: |
        [Unit]
        Description=Create etcd data dir and set ownership
        Requires=var-lib-etcd2.mount
        After=var-lib-etcd2.mount
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/mkdir -p /var/lib/etcd2/data
        ExecStart=/usr/bin/chown -R etcd:etcd /var/lib/etcd2/data
